name: test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - ocaml.5.2.0

    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: brew install postgresql@15 && brew link --overwrite postgresql@15
        if: runner.os == 'macOS'

      - uses: actions/cache@v4
        with:
          path: ~/.opam
          key: deps-${{ hashFiles('dream.opam') }}

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Test
        run: |
          opam exec -- dune exec -- example/1-hello/hello.exe &
          sleep 1;
          for (( i=0; i<1024; ++i )) ; do echo connecting; curl -s http://localhost:8080/ ; done

      - run: opam clean
